[package]
name = "scouting-backend-865"
version = "0.1.0"
edition = "2024"

[dependencies]
gcp_auth = "0.12.3"
non-empty-string = { version = "0.2.5", features = ["serde"] }
rocket = "0.5.1"
serde = "1.0.218"
serde_json = "1.0.139"
sheets = "0.7.0"
